# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: recsys.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List, Optional

import betterproto
import grpclib


@dataclass
class Field(betterproto.Message):
    value: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class Item(betterproto.Message):
    fields: List["Field"] = betterproto.message_field(1)


@dataclass
class Context(betterproto.Message):
    fields: List["Field"] = betterproto.message_field(1)


@dataclass
class ScoreRequest(betterproto.Message):
    items: List["Item"] = betterproto.message_field(1)
    context: "Context" = betterproto.message_field(2)


@dataclass
class ScoreResponse(betterproto.Message):
    scores: List[float] = betterproto.double_field(1)


class RecsysProxyCacheStub(betterproto.ServiceStub):
    async def get_scores(
        self, *, items: List["Item"] = [], context: Optional["Context"] = None
    ) -> ScoreResponse:
        request = ScoreRequest()
        if items is not None:
            request.items = items
        if context is not None:
            request.context = context

        return await self._unary_unary(
            "/recsys.RecsysProxyCache/GetScores",
            request,
            ScoreResponse,
        )
