version: "3.9"

services:

  recsys-1:
    build: ./recsys
    environment:
      GRPC_VERBOSITY: debug
      TCP_USER_TIMEOUT: 250
      MAX_CONNECTION_AGE: 1000
    networks:
      recsys-static-network:

  #recsys_2:
  #  build: ./recsys
  #  environment:
  #    GRPC_VERBOSITY: debug
  #    TCP_USER_TIMEOUT: 250
  #    MAX_CONNECTION_AGE: 1000
  #  networks:
  #    recsys-static-network:
  #      ipv4_address: "172.21.128.2" 

  #recsys_3:
  #  build: ./recsys
  #  environment:
  #    GRPC_VERBOSITY: debug
  #    TCP_USER_TIMEOUT: 250
  #    MAX_CONNECTION_AGE: 1000
  #  networks:
  #    recsys-static-network:
  #      ipv4_address: "172.21.128.3" 

  #lookaside-load-balancer:
  #  build: ./lookaside_load_balancer
  #  depends_on:
  #    - recsys_1
  #    - recsyr_2
  #    - recsys_3
  #  networks:
  #    recsys-static-network:

  recsys-proxy-cache:
    build:
      context: ./recsys-proxy-cache/java
    environment:
      RECSYS_TARGET: recsys-1:8500
      JAVA_OPTS: "-XX:+UseShenandoahGC -Xlog:gc+stats -XX:+AlwaysPreTouch -Xlog:async -XX:+UseTransparentHugePages -XX:+UseNUMA -XX:-UseBiasedLocking -XX:+DisableExplicitGC -Xms6G -Xmx6G -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      # debug port
      - 5005:5005
      - 50051:50051
    depends_on:
      - recsys-1
    networks:
      recsys-static-network:

  tests:
    profiles: [ "docker-compose-run-only" ]
    build:
      context: ./tests
    environment:
      RECSYS_PROXY_CACHE_TARGET: "recsys-proxy-cache:50051"
    volumes:
      - ./tests:/app
    networks:
      recsys-static-network:
    depends_on:
      - recsys-proxy-cache

networks:
  recsys-static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
