#!/bin/bash

PROJECT_NAME=recsysproxycache.daemon
case "$1" in
    stop)
        echo -ne "Stopping doggy-recsysproxycachedaemon... "
        sudo docker-compose -f ./docker-compose-deploy-vm.yml --project-name $PROJECT_NAME down
        ;;
    restart | graceful-restart | start)
        echo -ne "Restarting doggy-recsysproxycachedaemon... "
        cat ./docker-compose-deploy-vm.yml

        sudo docker-compose -f ./docker-compose-deploy-vm.yml --project-name $PROJECT_NAME down
        echo "Docker stop Exit Code: $?"

        sudo docker-compose -f ./docker-compose-deploy-vm.yml pull

        sudo docker-compose -f ./docker-compose-deploy-vm.yml --project-name $PROJECT_NAME up -d --force-recreate
        echo "Docker up Exit Code: $?"
        ;;
    status)
        echo -ne "Checking doggy-recsysproxycachedaemon status... "
        attempt="0"

        while [ $attempt -lt 15 ]
        do
            sudo docker ps
            sudo docker ps -f "name=recsysproxycache.daemon" | grep "recsysproxycache"
            webserviceRetVal=$?

            if [ $webserviceRetVal -ne 0 ]; then
                echo "recsysproxycache.daemon is not running. Attempt: $attempt"
                attempt=$[$attempt + 1]
                sleep 2;
            else
                echo "Services are running. Attempt: $attempt"
                exit 0
            fi
        done

        echo "Couldn't find running instance of dependent containers"
        exit 1
        ;;
    self-test)
        exit 0
        ;;
    *)
        echo "Usage: "$0" {start|stop|restart|graceful-restart|status|self-test}"
        exit 1
esac

exit $?
